version: '3.8'

services:
    web:
        image: jitsi/web:stable-10008
        restart: always
        ports:
            - '8080:80'
            - '${PORT}:443'
        volumes:
            - web_config:/config:Z
            - transcripts:/usr/share/jitsi-meet/transcripts:Z
        environment:
            - DISABLE_HTTPS=1
            - ENABLE_HTTP_REDIRECT=0
            - PUBLIC_URL=${PUBLIC_URL}
            - XMPP_SERVER=prosody
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=auth.${XMPP_DOMAIN}
            - XMPP_GUEST_DOMAIN=guest.${XMPP_DOMAIN}
            - XMPP_MUC_DOMAIN=muc.${XMPP_DOMAIN}
            - XMPP_RECORDER_DOMAIN=recorder.${XMPP_DOMAIN}
            - ENABLE_AUTH=${ENABLE_AUTH:-0}
            - ENABLE_GUESTS=${ENABLE_GUESTS:-1}
            - ENABLE_RECORDING=${ENABLE_RECORDING:-0}
        networks:
            meet.jitsi:
        depends_on:
            - prosody

    prosody:
        image: jitsi/prosody:stable-10008
        restart: always
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - prosody_config:/config:Z
        environment:
            - PUBLIC_URL=${PUBLIC_URL}
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=auth.${XMPP_DOMAIN}
            - XMPP_GUEST_DOMAIN=guest.${XMPP_DOMAIN}
            - XMPP_MUC_DOMAIN=muc.${XMPP_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${XMPP_DOMAIN}
            - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET}
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
            - ENABLE_AUTH=${ENABLE_AUTH:-0}
            - ENABLE_GUESTS=${ENABLE_GUESTS:-1}
        networks:
            meet.jitsi:
                aliases:
                    - prosody

    jicofo:
        image: jitsi/jicofo:stable-10008
        restart: always
        volumes:
            - jicofo_config:/config:Z
        environment:
            - XMPP_DOMAIN=${XMPP_DOMAIN}
            - XMPP_AUTH_DOMAIN=auth.${XMPP_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${XMPP_DOMAIN}
            - XMPP_SERVER=prosody
            - JICOFO_COMPONENT_SECRET=${JICOFO_COMPONENT_SECRET}
            - JVB_BREWERY_MUC=jvbbrewery
            - ENABLE_AUTH=${ENABLE_AUTH:-0}
        depends_on:
            - prosody
        networks:
            meet.jitsi:

    jvb:
        image: jitsi/jvb:stable-10008
        restart: always
        ports:
            - '${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp'
        volumes:
            - jvb_config:/config:Z
        environment:
            - DOCKER_HOST_ADDRESS=${DOCKER_HOST_ADDRESS}
            - XMPP_AUTH_DOMAIN=auth.${XMPP_DOMAIN}
            - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.${XMPP_DOMAIN}
            - XMPP_SERVER=prosody
            - JVB_AUTH_USER=jvb
            - JVB_AUTH_PASSWORD=${JVB_AUTH_PASSWORD}
            - JVB_BREWERY_MUC=jvbbrewery
            - JVB_PORT=${JVB_PORT:-10000}
            - PUBLIC_URL=${PUBLIC_URL}
        depends_on:
            - prosody
        networks:
            meet.jitsi:

networks:
    meet.jitsi:

volumes:
    web_config:
    prosody_config:
    jicofo_config:
    jvb_config:
    transcripts:
