#!/bin/bash
JICOFO_COMPONENT_SECRET=$(openssl rand -hex 16)
JICOFO_AUTH_PASSWORD=$(openssl rand -hex 16)
JVB_AUTH_PASSWORD=$(openssl rand -hex 16)

sed -i.bak \
    -e "s#JICOFO_COMPONENT_SECRET=#JICOFO_COMPONENT_SECRET=$JICOFO_COMPONENT_SECRET#g" \
    -e "s#JICOFO_AUTH_PASSWORD=#JICOFO_AUTH_PASSWORD=$JICOFO_AUTH_PASSWORD#g" \
    -e "s#JVB_AUTH_PASSWORD=#JVB_AUTH_PASSWORD=$JVB_AUTH_PASSWORD#g" \
    .env
