services:
  - type: web
    name: jitsi-web
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENABLE_AUTH
        value: "1"
      - key: ENABLE_GUESTS
        value: "1"
      - key: XMPP_DOMAIN
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: ENABLE_HTTP_REDIRECT
        value: "1"
      - key: ENABLE_LETSENCRYPT
        value: "1"
      - key: LETSENCRYPT_EMAIL
        sync: false
      - key: LETSENCRYPT_DOMAIN
        sync: false
    disk:
      name: jitsi-config
      mountPath: /config
      sizeGB: 10
    healthCheckPath: /about/health
    ports:
      - port: 80
        protocol: http
      - port: 443
        protocol: https
