services:
  - type: web
    name: jitsi-meet
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    healthCheckPath: /
    envVars:
      - key: ENABLE_AUTH
        value: "1"
      - key: ENABLE_GUESTS
        value: "1"
      - key: AUTH_TYPE
        value: "jwt"
      - key: XMPP_DOMAIN
        fromService:
          name: jitsi-meet
          type: web
          envVarKey: RENDER_EXTERNAL_HOSTNAME
      - key: PUBLIC_URL
        fromService:
          name: jitsi-meet
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: ENABLE_LETSENCRYPT
        value: "1"
      - key: ENABLE_HTTP_REDIRECT
        value: "1"
      - key: TZ
        value: "UTC"
    disk:
      name: jitsi-data
      mountPath: /root/.jitsi-meet-cfg
      sizeGB: 10
