services:
  - type: web
    name: jitsi-web
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENABLE_AUTH
        value: "1"
      - key: ENABLE_GUESTS
        value: "1"
      - key: PUBLIC_URL
        fromService:
          name: jitsi-web
          type: web
          property: host
      - key: XMPP_DOMAIN
        fromService:
          name: jitsi-web
          type: web
          property: host
      - key: XMPP_SERVER
        value: "xmpp.meet.jitsi"
      - key: JICOFO_AUTH_USER
        value: "focus"
    healthCheckPath: /
    disk:
      name: jitsi-config
      mountPath: /config
      sizeGB: 10

  - type: web
    name: prosody
    env: docker
    dockerfilePath: ./prosody.Dockerfile
    envVars:
      - key: XMPP_DOMAIN
        fromService:
          name: jitsi-web
          type: web
          property: host

  - type: web
    name: jicofo
    env: docker
    dockerfilePath: ./jicofo.Dockerfile
    envVars:
      - key: XMPP_DOMAIN
        fromService:
          name: jitsi-web
          type: web
          property: host

  - type: web
    name: jvb
    env: docker
    dockerfilePath: ./jvb.Dockerfile
    envVars:
      - key: XMPP_DOMAIN
        fromService:
          name: jitsi-web
          type: web
          property: host
